[package]
name = "openssl-sys"
version = "0.9.80"
authors = [
    "Alex Crichton <alex@alexcrichton.com>",
    "Steven Fackler <sfackler@gmail.com>",
]
license = "MIT"
description = "FFI bindings to OpenSSL"
repository = "https://github.com/sfackler/rust-openssl"
readme = "README.md"
categories = ["cryptography", "external-ffi-bindings"]
links = "openssl"
build = "build/main.rs"

[features]
vendored = ['tongsuo-p832-src']
unstable_boringssl = []
tongsuo = []
default = ["tongsuo","vendored"]

[dependencies]
libc = "0.2"
#bssl-sys = { version = "0.1.0", optional = true }

[build-dependencies]
bindgen = { version = "0.65.1", optional = true }
cc = "1.0"
#tongsuo-p832-src = { git="https://github.com/zh-jq/tongsuo-src-rs",optional=true,branch="patch-8.3.2" }
tongsuo-p832-src = {version = "*",optional=true}
pkg-config = "0.3.9"
autocfg = "1.0"

[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2.8"

# We don't actually use metadeps for annoying reasons but this is still here for tooling
[package.metadata.pkg-config]
openssl = "1.0.1"
